spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    department:
      jdbc-url: jdbc:mysql://localhost:3306/department_db
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

    employee:
      jdbc-url: jdbc:mysql://localhost:3306/employee_db
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
